### PR TITLE
Upgrade pyo3 to 0.20

### PR DESCRIPTION
**Pull request by messense**
https://github.com/PyO3/pyo3/releases/tag/v0.20.0

### CODE REVIEW

**Comment by ritchie46** [comment]
Thanks!

**Comment by messense** [comment]
Could you release a new version to crates.io? Thanks!

**Comment by aldanor** [comment]
@messense I'm guessing next version will have to wait until the new expression api is stabilized and released in polars-core.

**Comment by ritchie46** [comment]
Yes, we are currently blocked by https://github.com/tkaitchuck/aHash/issues/166.

Once that patch is merged we can release.

**Comment by aldanor** [comment]
New version of ahash is now out.

**Pull request merged**
