### PR TITLE
Bump pyo3 from 0.21 to 0.22

### PR DESCRIPTION
**Pull request by akhilles**
Fixes: https://github.com/pola-rs/pyo3-polars/issues/86

### CODE REVIEW

**Comment by sheldonrong** [comment]
@ritchie46 can you help review this change? thanks!

**Comment by ritchie46** [comment]
It requires a bit more to go the bound api. That also needs code changes.

**Comment by sheldonrong** [comment]
any progresses yet?

**Comment by ritchie46** [comment]
Thanks. resolved by #93

**Pull request closed without merging**
